name: VisualStudio

on: [push, pull_request]

jobs:
  GeneralTest:
    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.11.0
    
    - name: Invoking makefile
      working-directory: ./auto-test
      run: nmake 
      
    - name: Run Test Program
      run: dir

